name: "Setup PNPM"
description: "Sets up Node.js, PNPM, and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Restore pnpm cache
      id: pnpm-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Save pnpm cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: ~/.pnpm-store
        key: ${{ steps.pnpm-cache-restore.outputs.cache-primary-key }}
