import type { Policy } from "./Policy.type.js";

// Input type for creating a new Policy (initial version or subsequent)
// Omits fields generated by the system (id, createdAt, updatedAt, version)
// or fields managed by the service layer (policyGroupId for subsequent versions).
export type CreatePolicyInput = Omit<
  Policy,
  "id" | "createdAt" | "updatedAt" // Version is now allowed and expected from service layer
>;

// Input type for the data defining a new version of an existing policy.
// It omits system-generated fields and also policyGroupId and version,
// as those will be derived by the PolicyService from the policy being superseded.
export type NewPolicyVersionDataInput = Omit<
  Policy,
  "id" | "policyGroupId" | "version" | "createdAt" | "updatedAt"
>;
